"""Add sensor equation fields

Revision ID: 06d7ff353efa
Revises: 65b08aa7e6b2
Create Date: 2024-02-16 11:13:38.791610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '06d7ff353efa'
down_revision: Union[str, None] = '65b08aa7e6b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('slope', sa.Float(), nullable=True))
    op.add_column('sensor', sa.Column('intercept', sa.Float(), nullable=True))
    op.add_column('sensor', sa.Column('min_range', sa.Float(), nullable=True))
    op.add_column('sensor', sa.Column('max_range', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor', 'max_range')
    op.drop_column('sensor', 'min_range')
    op.drop_column('sensor', 'intercept')
    op.drop_column('sensor', 'slope')
    # ### end Alembic commands ###
