"""Remove SensorID

Revision ID: 09651fa5f642
Revises: 123f25fa96a8
Create Date: 2024-04-18 10:15:57.084446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '09651fa5f642'
down_revision: Union[str, None] = '123f25fa96a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sensorparameter_sensor_id', table_name='sensorparameter')
    op.drop_column('sensorparameter', 'sensor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensorparameter', sa.Column('sensor_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index('ix_sensorparameter_sensor_id', 'sensorparameter', ['sensor_id'], unique=False)
    # ### end Alembic commands ###
