"""Add sensor ID to parameter

Revision ID: 123f25fa96a8
Revises: 48f707deaf66
Create Date: 2024-04-17 17:14:27.239310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '123f25fa96a8'
down_revision: Union[str, None] = '48f707deaf66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensorparameter', sa.Column('sensor_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.create_index(op.f('ix_sensorparameter_sensor_id'), 'sensorparameter', ['sensor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensorparameter_sensor_id'), table_name='sensorparameter')
    op.drop_column('sensorparameter', 'sensor_id')
    # ### end Alembic commands ###
