"""Set unique constraint to messageGuid

Revision ID: 24f8948791d7
Revises: b4112755acc4
Create Date: 2024-01-24 11:42:21.977676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '24f8948791d7'
down_revision: Union[str, None] = 'b4112755acc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_id_constraint', 'astrocastmessage', type_='unique')
    op.create_unique_constraint(None, 'astrocastmessage', ['messageGuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'astrocastmessage', type_='unique')
    op.create_unique_constraint('unique_id_constraint', 'astrocastmessage', ['id', 'messageGuid'])
    # ### end Alembic commands ###
