"""Add iterators and retrieved at for Astrocast message - again

Revision ID: 258bcd22c26c
Revises: cc936ce6e67b
Create Date: 2024-01-24 11:07:55.725699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '258bcd22c26c'
down_revision: Union[str, None] = 'cc936ce6e67b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
