"""Add unique message constraint

Revision ID: 30c99808d7f4
Revises: d1abed5ee378
Create Date: 2024-01-24 11:38:28.192863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '30c99808d7f4'
down_revision: Union[str, None] = 'd1abed5ee378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('astrocastmessage_id_key', 'astrocastmessage', type_='unique')
    op.create_unique_constraint(None, 'astrocastmessage', ['id', 'messageGuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'astrocastmessage', type_='unique')
    op.create_unique_constraint('astrocastmessage_id_key', 'astrocastmessage', ['id'])
    # ### end Alembic commands ###
