"""Set field ID to non-null

Revision ID: 483ca00f1861
Revises: 5e3ae1f92272
Create Date: 2024-05-01 15:46:35.714085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '483ca00f1861'
down_revision: Union[str, None] = '5e3ae1f92272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sensor', 'field_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sensor', 'field_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
