"""Add fields to station data

Revision ID: 48f707deaf66
Revises: 3293bb5fb929
Create Date: 2024-04-17 10:11:26.061539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '48f707deaf66'
down_revision: Union[str, None] = '3293bb5fb929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_stationdata_high_resolution'), 'stationdata', ['high_resolution'], unique=False)
    op.create_index(op.f('ix_stationdata_last_updated'), 'stationdata', ['last_updated'], unique=False)
    op.create_index(op.f('ix_stationdata_parameter_id'), 'stationdata', ['parameter_id'], unique=False)
    op.create_index(op.f('ix_stationdata_sensor_id'), 'stationdata', ['sensor_id'], unique=False)
    op.create_index(op.f('ix_stationdata_station_id'), 'stationdata', ['station_id'], unique=False)
    op.create_index(op.f('ix_stationdata_time'), 'stationdata', ['time'], unique=False)
    op.create_index(op.f('ix_stationdata_value'), 'stationdata', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stationdata_value'), table_name='stationdata')
    op.drop_index(op.f('ix_stationdata_time'), table_name='stationdata')
    op.drop_index(op.f('ix_stationdata_station_id'), table_name='stationdata')
    op.drop_index(op.f('ix_stationdata_sensor_id'), table_name='stationdata')
    op.drop_index(op.f('ix_stationdata_parameter_id'), table_name='stationdata')
    op.drop_index(op.f('ix_stationdata_last_updated'), table_name='stationdata')
    op.drop_index(op.f('ix_stationdata_high_resolution'), table_name='stationdata')
    # ### end Alembic commands ###
