"""Add foreign key relationship to sensor's parameter_id

Revision ID: 4ccae82ccb31
Revises: d057ad1a2a31
Create Date: 2024-04-18 11:16:25.190583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4ccae82ccb31'
down_revision: Union[str, None] = 'd057ad1a2a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'sensor', 'sensorparameter', ['parameter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensor', type_='foreignkey')
    # ### end Alembic commands ###
