"""Add unique field ID

Revision ID: 5e3ae1f92272
Revises: 7c704b70a373
Create Date: 2024-05-01 15:44:38.929215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5e3ae1f92272'
down_revision: Union[str, None] = '7c704b70a373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('field_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_unique_constraint('unique_sensor_field_id', 'sensor', ['field_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_sensor_field_id', 'sensor', type_='unique')
    op.drop_column('sensor', 'field_id')
    # ### end Alembic commands ###
