"""Modify unique constraint to prevent multiple of sensor, or sensor positions

Revision ID: 65b08aa7e6b2
Revises: 955228ff23fc
Create Date: 2024-02-15 15:24:43.644319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '65b08aa7e6b2'
down_revision: Union[str, None] = '955228ff23fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sensor_station_position_unique_constraint', 'stationsensorassignments', type_='unique')
    op.create_unique_constraint('no_multiple_sensors_assigned_constraint', 'stationsensorassignments', ['sensor_id'])
    op.create_unique_constraint('sensor_position_constraint', 'stationsensorassignments', ['station_id', 'sensor_position'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sensor_position_constraint', 'stationsensorassignments', type_='unique')
    op.drop_constraint('no_multiple_sensors_assigned_constraint', 'stationsensorassignments', type_='unique')
    op.create_unique_constraint('sensor_station_position_unique_constraint', 'stationsensorassignments', ['station_id', 'sensor_id'])
    # ### end Alembic commands ###
