"""Add control message table

Revision ID: 7c704b70a373
Revises: d800b9910102
Create Date: 2024-05-01 11:38:25.267484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7c704b70a373'
down_revision: Union[str, None] = 'd800b9910102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controlmessage',
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('astrocast_message_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('station_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('iterator', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['astrocast_message_id'], ['astrocastmessage.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
    sa.PrimaryKeyConstraint('iterator'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_controlmessage_astrocast_message_id'), 'controlmessage', ['astrocast_message_id'], unique=False)
    op.create_index(op.f('ix_controlmessage_id'), 'controlmessage', ['id'], unique=False)
    op.create_index(op.f('ix_controlmessage_iterator'), 'controlmessage', ['iterator'], unique=False)
    op.create_index(op.f('ix_controlmessage_received_at'), 'controlmessage', ['received_at'], unique=False)
    op.create_index(op.f('ix_controlmessage_station_id'), 'controlmessage', ['station_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_controlmessage_station_id'), table_name='controlmessage')
    op.drop_index(op.f('ix_controlmessage_received_at'), table_name='controlmessage')
    op.drop_index(op.f('ix_controlmessage_iterator'), table_name='controlmessage')
    op.drop_index(op.f('ix_controlmessage_id'), table_name='controlmessage')
    op.drop_index(op.f('ix_controlmessage_astrocast_message_id'), table_name='controlmessage')
    op.drop_table('controlmessage')
    # ### end Alembic commands ###
