"""Add Astrocast message table

Revision ID: 7eb7e5593609
Revises: 63afeb63c97d
Create Date: 2024-01-24 10:58:53.985348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7eb7e5593609'
down_revision: Union[str, None] = '63afeb63c97d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('time_added_utc', sa.DateTime(), nullable=True))
    op.drop_index('ix_sensor_time_recorded_at_utc', table_name='sensor')
    op.create_index(op.f('ix_sensor_time_added_utc'), 'sensor', ['time_added_utc'], unique=False)
    op.drop_column('sensor', 'elevation')
    op.drop_column('sensor', 'time_recorded_at_utc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('time_recorded_at_utc', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('sensor', sa.Column('elevation', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_sensor_time_added_utc'), table_name='sensor')
    op.create_index('ix_sensor_time_recorded_at_utc', 'sensor', ['time_recorded_at_utc'], unique=False)
    op.drop_column('sensor', 'time_added_utc')
    # ### end Alembic commands ###
