"""Modify unique constraint

Revision ID: 955228ff23fc
Revises: 5a7ba47c4fc9
Create Date: 2024-02-15 12:14:55.295930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '955228ff23fc'
down_revision: Union[str, None] = '5a7ba47c4fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sensor_station_position_unique_constraint', 'stationsensorassignments', type_='unique')
    op.create_unique_constraint('sensor_station_position_unique_constraint', 'stationsensorassignments', ['station_id', 'sensor_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sensor_station_position_unique_constraint', 'stationsensorassignments', type_='unique')
    op.create_unique_constraint('sensor_station_position_unique_constraint', 'stationsensorassignments', ['sensor_position', 'station_id', 'sensor_id'])
    # ### end Alembic commands ###
