"""Remove nullable and unique constraint on sensor_id

Revision ID: 9fd7e97a72af
Revises: 483ca00f1861
Create Date: 2024-05-01 20:45:45.559041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9fd7e97a72af'
down_revision: Union[str, None] = '483ca00f1861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stationsensorassignments', 'sensor_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('no_multiple_sensors_assigned_constraint', 'stationsensorassignments', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('no_multiple_sensors_assigned_constraint', 'stationsensorassignments', ['sensor_id'])
    op.alter_column('stationsensorassignments', 'sensor_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
