"""Fix inheritance of SensorCalibration to create table

Revision ID: af1563ce9135
Revises: 599535d5770f
Create Date: 2024-02-16 15:58:09.856932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'af1563ce9135'
down_revision: Union[str, None] = '599535d5770f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensorcalibration', 'model')
    op.drop_column('sensorcalibration', 'parameter_acronym')
    op.drop_column('sensorcalibration', 'parameter_unit')
    op.drop_column('sensorcalibration', 'parameter_name')
    op.drop_column('sensorcalibration', 'serial_number')
    op.drop_column('sensorcalibration', 'parameter_db_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensorcalibration', sa.Column('parameter_db_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sensorcalibration', sa.Column('serial_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sensorcalibration', sa.Column('parameter_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sensorcalibration', sa.Column('parameter_unit', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sensorcalibration', sa.Column('parameter_acronym', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sensorcalibration', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
