"""Add unique message constraint 2

Revision ID: b4112755acc4
Revises: 30c99808d7f4
Create Date: 2024-01-24 11:40:11.387541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "b4112755acc4"
down_revision: Union[str, None] = "30c99808d7f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "astrocastmessage_id_messageGuid_key",
        "astrocastmessage",
        type_="unique",
    )
    op.create_unique_constraint(
        "unique_id_constraint", "astrocastmessage", ["id", "messageGuid"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "unique_id_constraint", "astrocastmessage", type_="unique"
    )
    op.create_unique_constraint(
        "astrocastmessage_id_messageGuid_key",
        "astrocastmessage",
        ["id", "messageGuid"],
    )
    # ### end Alembic commands ###
