"""Reconfigure name of astrocast table

Revision ID: b5636e7bfb97
Revises: 258bcd22c26c
Create Date: 2024-01-24 11:09:47.842200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b5636e7bfb97'
down_revision: Union[str, None] = '258bcd22c26c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
