"""Modify coordinates to metadata instead of geom object

Revision ID: b85486f4fec0
Revises: b27476d04638
Create Date: 2024-02-13 15:53:15.833346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = 'b85486f4fec0'
down_revision: Union[str, None] = 'b27476d04638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('x_coordinate', sa.Float(), nullable=True))
    op.add_column('station', sa.Column('y_coordinate', sa.Float(), nullable=True))
    op.drop_geospatial_index('idx_station_geom', table_name='station', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_column('station', 'geom')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_geospatial_column('station', sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), autoincrement=False, nullable=True))
    op.create_geospatial_index('idx_station_geom', 'station', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.drop_column('station', 'y_coordinate')
    op.drop_column('station', 'x_coordinate')
    # ### end Alembic commands ###
