"""Add iterators and retrieved at for Astrocast message

Revision ID: cc936ce6e67b
Revises: 7eb7e5593609
Create Date: 2024-01-24 11:07:43.792583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cc936ce6e67b'
down_revision: Union[str, None] = '7eb7e5593609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
