"""Add astrocast table

Revision ID: d1abed5ee378
Revises: b5636e7bfb97
Create Date: 2024-01-24 11:18:08.766916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd1abed5ee378'
down_revision: Union[str, None] = 'b5636e7bfb97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('astrocastmessage',
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('messageGuid', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('deviceGuid', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('receivedDate', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('messageSize', sa.Integer(), nullable=True),
    sa.Column('callbackDeliveryStatus', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('iterator', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('iterator'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_astrocastmessage_id'), 'astrocastmessage', ['id'], unique=False)
    op.create_index(op.f('ix_astrocastmessage_iterator'), 'astrocastmessage', ['iterator'], unique=False)
    op.create_index(op.f('ix_astrocastmessage_requested_at'), 'astrocastmessage', ['requested_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_astrocastmessage_requested_at'), table_name='astrocastmessage')
    op.drop_index(op.f('ix_astrocastmessage_iterator'), table_name='astrocastmessage')
    op.drop_index(op.f('ix_astrocastmessage_id'), table_name='astrocastmessage')
    op.drop_table('astrocastmessage')
    # ### end Alembic commands ###
